### ISSUE TITLE
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' } 

### ISSUE THREAD

**Issue by jdcarroll** [seelio/mongojsom#4]
Why am I getting this error message?
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by kyriesent** [comment]
Looks like the c++ extension failed to compile. From the error, it looks like your code will still run, though.

Might want to make sure your C++ compiler is functioning correctly during `npm install`.

**Comment by vkareh** [comment]
@jdcarroll, is it possible that you're running `npm install` on a host system and then running the application in a container with a different architecture? (e.g. using Docker) That would likely cause this module dependency to fail as well.

As @kyriesent said, it might not have compiled properly - I would suggest reinstalling the module and looking at the `npm-debug.log` file if it fails again.

**Comment by jdcarroll** [comment]
Im not using docker, and everything that I want to do with it works I just get the message.  I have tried uninstalling and reinstalling and and still getting the same error. its not really a problem just curiosity got the best of me. thank you guys for responding so quickly.
